#include <vector>

#pragma once

class CLocale
{
public:
	static enum
	{
		ID_START_MESSAGE = 1,
		ID_E_UNEXPECTED,
		ID_E_FAIL,
		ID_E_NOINTERFACE,
		ID_E_INVALIDARG,
		ID_DB_E_BADACCESSORHANDLE,
		ID_DB_E_ROWLIMITEXCEEDED,
		ID_DB_E_READONLYACCESSOR,
		ID_DB_E_SCHEMAVIOLATION,
		ID_DB_E_BADROWHANDLE,
		ID_DB_E_OBJECTOPEN,
		ID_DB_E_BADCHAPTER,
		ID_DB_E_CANTCONVERTVALUE,
		ID_DB_E_BADBINDINFO,
		ID_DB_SEC_E_PERMISSIONDENIED,
		ID_DB_E_NOTAREFERENCECOLUMN,
		ID_DB_E_LIMITREJECTED,
		ID_DB_E_NOCOMMAND,
		ID_DB_E_COSTLIMIT,
		ID_DB_E_BADBOOKMARK,
		ID_DB_E_BADLOCKMODE,
		ID_DB_E_PARAMNOTOPTIONAL,
		ID_DB_E_BADCOLUMNID,
		ID_DB_E_BADRATIO,
		ID_DB_E_BADVALUES,
		ID_DB_E_ERRORSINCOMMAND,
		ID_DB_E_CANTCANCEL,
		ID_DB_E_DIALECTNOTSUPPORTED,
		ID_DB_E_DUPLICATEDATASOURCE,
		ID_DB_E_CANNOTRESTART,
		ID_DB_E_NOTFOUND,
		ID_DB_E_NEWLYINSERTED,
		ID_DB_E_CANNOTFREE,
		ID_DB_E_GOALREJECTED,
		ID_DB_E_UNSUPPORTEDCONVERSION,
		ID_DB_E_BADSTARTPOSITION,
		ID_DB_E_NOQUERY,
		ID_DB_E_NOTREENTRANT,
		ID_DB_E_ERRORSOCCURRED,
		ID_DB_E_NOAGGREGATION,
		ID_DB_E_DELETEDROW,
		ID_DB_E_CANTFETCHBACKWARDS,
		ID_DB_E_ROWSNOTRELEASED,
		ID_DB_E_BADSTORAGEFLAG,
		ID_DB_E_BADCOMPAREOP,
		ID_DB_E_BADSTATUSVALUE,
		ID_DB_E_CANTSCROLLBACKWARDS,
		ID_DB_E_BADREGIONHANDLE,
		ID_DB_E_NONCONTIGUOUSRANGE,
		ID_DB_E_INVALIDTRANSITION,
		ID_DB_E_NOTASUBREGION,
		ID_DB_E_MULTIPLESTATEMENTS,
		ID_DB_E_INTEGRITYVIOLATION,
		ID_DB_E_BADTYPENAME,
		ID_DB_E_ABORTLIMITREACHED,
		ID_DB_E_ROWSETINCOMMAND,
		ID_DB_E_CANTTRANSLATE,
		ID_DB_E_DUPLICATEINDEXID,
		ID_DB_E_NOINDEX,
		ID_DB_E_INDEXINUSE,
		ID_DB_E_NOTABLE,
		ID_DB_E_CONCURRENCYVIOLATION,
		ID_DB_E_BADCOPY,
		ID_DB_E_BADPRECISION,
		ID_DB_E_BADSCALE,
		ID_DB_E_BADTABLEID,
		ID_DB_E_BADTYPE,
		ID_DB_E_DUPLICATECOLUMNID,
		ID_DB_E_DUPLICATETABLEID,
		ID_DB_E_TABLEINUSE,
		ID_DB_E_NOLOCALE,
		ID_DB_E_BADRECORDNUM,
		ID_DB_E_BOOKMARKSKIPPED,
		ID_DB_E_BADPROPERTYVALUE,
		ID_DB_E_INVALID,
		ID_DB_E_BADACCESSORFLAGS,
		ID_DB_E_BADSTORAGEFLAGS,
		ID_DB_E_BYREFACCESSORNOTSUPPORTED,
		ID_DB_E_NULLACCESSORNOTSUPPORTED,
		ID_DB_E_NOTPREPARED,
		ID_DB_E_BADACCESSORTYPE,
		ID_DB_E_WRITEONLYACCESSOR,
		ID_DB_SEC_E_AUTH_FAILED,
		ID_DB_E_CANCELED,
		ID_DB_E_CHAPTERNOTRELEASED,
		ID_DB_E_BADSOURCEHANDLE,
		ID_DB_E_PARAMUNAVAILABLE,
		ID_DB_E_ALREADYINITIALIZED,
		ID_DB_E_NOTSUPPORTED,
		ID_DB_E_MAXPENDCHANGESEXCEEDED,
		ID_DB_E_BADORDINAL,
		ID_DB_E_PENDINGCHANGES,
		ID_DB_E_DATAOVERFLOW,
		ID_DB_E_BADHRESULT,
		ID_DB_E_BADLOOKUPID,
		ID_DB_E_BADDYNAMICERRORID,
		ID_DB_E_PENDINGINSERT,
		ID_DB_E_BADCONVERTFLAG,
		ID_DB_E_OBJECTMISMATCH,
		ID_DB_E_ERROR_DESCRIPTION,
		ID_DB_E_ERROR_GENERIC,
		ID_OBJECT_ZOMBIE_STATE,
		ID_MAX_MESSAGE
	};

	struct localizedMessages
	{
		int		msgId;
		WCHAR	*locale;
		WCHAR	*msg;
	};

	static CLocale::localizedMessages messages[];

	static WCHAR *Msg(int msgID, WCHAR *locale);
	static WCHAR *Msg(int msgID);
};

